spring.application.name: T1TrackTimeProject
#Liquibase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    datasource:
#      initialization-mode: never

server:
  port: 8080

